name: "Bug 反馈"
description: "报告 PCL.Nova.Plus 中的 Bug。"
labels: "bug"

title: "[Bug] "

body:
- type: checkboxes
  id: checklist
  attributes:
    label: "检查单"
    description: "请确认："
    options:
      - label: "我已将启动器更新至最新版。"
        required: true
      - label: "该问题没有被其他人报告过。"
        required: true
- type: textarea
  id: description
  attributes:
    label: 描述
    placeholder: "请详细描述遇到的问题。"
  validations:
    required: true
- type: textarea
  id: steps
  attributes:
    label: 复现方式
    placeholder: |
      1. xxx
      2. xxx
  validations:
    required: true
- type: textarea
  id: system
  attributes:
    label: 系统信息
    placeholder: "Windows 10"
  validations:
    required: true
