name: "Bug 反馈"
description: "报告 PCL.Nova.Plus 中出现的 Bug"
labels: "bug"

title: "[Bug] "

body:
- type: markdown
  attributes:
    value: |
      **请确认您已将启动器更新至最新版，并且该问题没有被报告过！查看 [Issue 列表](https://github.com/SupriseCandyShark/PCL.Nova.Plus/issues)**
- type: textarea
  id: description
  attributes:
    label: 问题描述
    placeholder: "详细描述遇到的问题"
  validations:
    required: true
- type: textarea
  id: steps
  attributes:
    label: 复现步骤
    placeholder: |
      1. xxx
      2. xxx
  validations:
    required: true
- type: textarea
  id: system
  attributes:
    label: 系统信息
    placeholder: "Windows 10"
  validations:
    required: true
