name: "新功能建议"
description: "为 PCL.Nova.Plus 提出一个建议"

title: "[Feature] "

body:
- type: markdown
  attributes:
    value: |
      **请确认该建议没有被其他人提出过！查看 [Issue 列表](https://github.com/SupriseCandyShark/PCL.Nova.Plus/issues)**
- type: textarea
  id: feature
  attributes:
    label: 描述
    placeholder: "请描述你需要的新功能"
  validations:
    required: true
- type: textarea
  id: scenario
  attributes:
    label: 原因
    placeholder: "为什么这个功能对你有帮助"
  validations:
    required: true
