name: Wails build

on:
    # push:
    #     branches: [main]
    workflow_dispatch:

env:
    NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                build:
                    # Linux amd64 构建
                    - name: "PCL.Nova.Plus-Linux-amd64"
                      platform: "linux/amd64"
                      os: "ubuntu-latest"
                      realOs: "Linux-amd64"
                    # Windows amd64 构建
                    - name: "PCL.Nova.Plus-Windows-amd64"
                      platform: "windows/amd64"
                      os: "windows-latest"
                      realOs: "Windows-amd64"
                    # macOS 通用 构建
                    - name: "PCL.Nova.Plus-macOS-universal"
                      platform: "darwin/universal"
                      os: "macos-latest"
                      realOs: "macOS-universal"
                    # Linux arm 构建
                    - name: "PCL.Nova.Plus-Linux-arm64"
                      platform: "linux/arm64"
                      os: "ubuntu-24.04-arm"
                      realOs: "Linux-arm64"

        runs-on: ${{ matrix.build.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - run: git config --global core.autocrlf input
            # - name: Install Wails
            #   uses: dAppServer/wails-build-action@main
            #   id: build
            #   with:
            #       build-name: ${{ matrix.build.name }}
            #       build-platform: ${{ matrix.build.platform }}
            #       go-version: "1.24"
            #       node-version: "23"
            #       package: false
            - name: Install Linux Dependency
              shell: bash
              if: runner.os == 'Linux'
              run: |
                  sudo apt-get -yq update
                  sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.1-dev gcc-aarch64-linux-gnu
            - name: Install Golang
              uses: actions/setup-go@v6
              with:
                  go-version: stable
            - name: Install Nodes
              uses: actions/setup-node@v5
              with:
                  node-version: 23
            - name: Install wails
              shell: bash
              run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
            - name: Read Version
              id: version
              shell: bash
              run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
            - name: Build Wails App
              if: ${{ matrix.build.os != 'windows-11-arm' }}
              shell: bash
              run: |
                  cfKey=${{secrets.CF_KEY}}
                  msKey=${{secrets.MS_KEY}}
                  lsKey=${{secrets.LS_KEY}}
                  pvKey=${{secrets.PV_KEY}}
                  ver=${{steps.version.outputs.version}}
                  rver=${ver%-*}
                  wails build -v 0 -tags webkit2_41,desktop,production -platform ${{matrix.build.platform}} -ldflags \
                  "-X 'NovaPlus/module/mmcll.LauncherVersion=${{steps.version.outputs.version}}' \
                  -X 'NovaPlus/module/mmcll.LauncherName=PCL.Nova.Plus' \
                  -X 'NovaPlus/module/mmcll.LauncherUserAgent=PCL.Nova.Plus/$rver' \
                  -X 'NovaPlus/module/launcher.CF_KEY=$cfKey' \
                  -X 'NovaPlus/module/launcher.MS_KEY=$msKey' \
                  -X 'NovaPlus/module/launcher.PV_KEY=$pvKey' \
                  -X 'NovaPlus/module/launcher.LS_KEY=$lsKey'"
              env:
                  CGO_ENABLED: 1
            - name: Rename Executable File
              shell: bash
              run: |
                  if [[ ${{matrix.build.os}} =~ "windows" ]]; then
                    mv ./build/bin/PCL.Nova.Plus.exe ./PCL.Nova.Plus-${{steps.version.outputs.version}}-${{matrix.build.realOs}}.exe
                  elif [[ "${{matrix.build.os}}" == "macos-latest" ]]; then
                    mkdir ./PCL.Nova.Plus-${{steps.version.outputs.version}}-${{matrix.build.realOs}}
                    mv ./build/bin/PCL.Nova.Plus.app ./PCL.Nova.Plus-${{steps.version.outputs.version}}-${{matrix.build.realOs}}/PCL.Nova.Plus.app
                  elif [[ "${{matrix.build.os}}" =~ "ubuntu" ]]; then
                    mv ./build/bin/PCL.Nova.Plus ./PCL.Nova.Plus-${{steps.version.outputs.version}}-${{matrix.build.realOs}}
                  fi
            - name: Upload all Artifacts Windows
              if: ${{matrix.build.os == 'windows-latest' || matrix.build.os == 'windows-11-arm'}}
              uses: actions/upload-artifact@v4
              with:
                  name: PCL-Nova-Plus-${{steps.version.outputs.version}}-${{matrix.build.realOs}}-Bundle
                  path: ./PCL.Nova.Plus-${{steps.version.outputs.version}}-${{matrix.build.realOs}}.exe
            - name: Upload all Artifacts macOS
              if: ${{matrix.build.os == 'macos-latest'}}
              uses: actions/upload-artifact@v4
              with:
                  name: PCL-Nova-Plus-${{steps.version.outputs.version}}-${{matrix.build.realOs}}-Bundle
                  path: ./PCL.Nova.Plus-${{steps.version.outputs.version}}-${{matrix.build.realOs}}
            - name: Upload all Artifacts Linux
              if: ${{matrix.build.os == 'ubuntu-24.04-arm' || matrix.build.os == 'ubuntu-latest'}}
              uses: actions/upload-artifact@v4
              with:
                  name: PCL-Nova-Plus-${{steps.version.outputs.version}}-${{matrix.build.realOs}}-Bundle
                  path: ./PCL.Nova.Plus-${{steps.version.outputs.version}}-${{matrix.build.realOs}}