name: Wails build

on:
    push:
        branches: [dev, main]

env:
    NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                build:
                    # Linux amd64 构建
                    - name: "PCL.Nova.Plus-Linux-amd64"
                      platform: "linux/amd64"
                      os: "ubuntu-latest"
                      realOs: "Linux-amd64"
                    # Windows amd64 构建
                    - name: "PCL.Nova.Plus-Windows-amd64"
                      platform: "windows/amd64"
                      os: "windows-latest"
                      realOs: "Windows-amd64"
                    # macOS 通用 构建
                    - name: "PCL.Nova.Plus-macOS-universal"
                      platform: "darwin/universal"
                      os: "macos-latest"
                      realOs: "macOS-universal"
                    # Linux arm 构建
                    - name: "PCL.Nova.Plus-Linux-arm64"
                      platform: "linux/arm64"
                      os: "ubuntu-24.04-arm"
                      realOs: "Linux-arm64"
                    # Windows arm 构建
                    - name: "PCL.Nova.Plus-Windows-arm64"
                      platform: "windows/arm64"
                      os: "windows-11-arm"
                      realOs: "Windows-arm64"

        runs-on: ${{ matrix.build.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Install Linux Dependency
              shell: bash
              if: runner.os == 'Linux'
              run: |
                  sudo apt-get -yq install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
            - name: Install Golang
              uses: actions/setup-go@v6
              with:
                  go-version: stable
            - name: Install Nodes
              uses: actions/setup-node@v5
              with:
                  node-version: 23
            - name: Install wails
              shell: bash
              run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
            - name: Read Version
              id: version
              shell: bash
              run: echo "version=$(cat Version)" >> $GITHUB_OUTPUT
            - name: Build Wails App
              shell: bash
              run: |
                  cfKey=${{secrets.CF_KEY}}
                  msKey=${{secrets.MS_KEY}}
                  lsKey=${{srcrets.LS_KEY}}
                  pvKey=${{secrets.PRIVATE_KEY}}
                  CGO_ENABLED=1 wails build -v 0 -platform ${{matrix.build.platform}} -ldflags \
                  "-X 'NovaPlus/module/mmcll.LauncherVersion=${{steps.version.outputs.version}}' \
                  -X 'NovaPlus/module/mmcll.LauncherName=PCL.Nova.Plus' \
                  -X 'NovaPlus/module/mmcll.LauncherUserAgent=PCL.Nova.Plus/${{steps.version.outputs.version}}' \
                  -X 'NovaPlus/module/launcher.XApiKey=$cfKey' \
                  -X 'NovaPlus/module/launcher.ClientId=$msKey' \
                  -X 'NovaPlus/module/launcher.PrivacyKey=$pvKey' \
                  -X 'NovaPlus/module/launcher.LittleSkinKey=$lsKey'"
            - name: Rename Executable File
              shell: bash
              run: |
                  if [[ ${{matrix.build.os}} =~ "windows" ]]; then
                    mv ./build/bin/PCL.Nova.Plus.exe ./PCL.Nova.Plus-${{steps.version.outputs.version}}-${{matrix.build.realOs}}.exe
                  elif [ "${{matrix.build.os}}" -eq "macos-latest" ]; then
                    zip -9 -r "./build/bin/PCL.Nova.Plus.app" .
                    mv ./build/bin/PCL.Nova.Plus.zip ./PCL.Nova.Plus-${{steps.version.outputs.version}}-${{matrix.build.realOs}}.zip
                  elif [[ "${{matrix.build.os}}" =~ "ubuntu" ]]; then
                    mv ./build/bin/PCL.Nova.Plus ./PCL.Nova.Plus-${{steps.version.outputs.version}}-${{matrix.build.realOs}}
                  fi
            - name: Upload all Artifacts Windows
              if: ${{matrix.build.os == 'windows-latest' || matrix.build.os == 'windows-11-arm64'}}
              uses: actions/upload-artifact@v4
              with:
                  name: PCL-Nova-Plus-${{steps.version.outputs.version}}-Beta-${{matrix.build.realOs}}-Bundle
                  path: ./PCL.Nova.Plus-${{steps.version.outputs.version}}-Beta-${{matrix.build.realOs}}.exe
            - name: Upload all Artifacts macOS
              if: ${{matrix.build.os == 'macos-latest'}}
              uses: actions/upload-artifact@v4
              with:
                  name: PCL-Nova-Plus-${{steps.version.outputs.version}}-Beta-${{matrix.build.realOs}}-Bundle
                  path: ./PCL.Nova.Plus-${{steps.version.outputs.version}}-Beta-${{matrix.build.realOs}}.zip
            - name: Upload all Artifacts macOS
              if: ${{matrix.build.os == 'ubuntu-24.04-arm' || matrix.build.os}}
              uses: actions/upload-artifact@v4
              with:
                  name: PCL-Nova-Plus-${{steps.version.outputs.version}}-Beta-${{matrix.build.realOs}}-Bundle
                  path: ./PCL.Nova.Plus-${{steps.version.outputs.version}}-Beta-${{matrix.build.realOs}}
